### ISSUE TITLE
backup location cannot contain certain characters

### ISSUE THREAD

**Issue by bbuckingham** [RedHatSatellite/satellite-clone#181]
This issue has been addressed in the upstream katello-backup; however, it may cause problems for users that do not have the fix.

Scenario:
- created a katello-backup on a Satellite 6.2.8 instance
- installed the backup on the server to perform the clone - the location of the backup was in: /root/satellite1_backup/katello-backup-2017-04-07T09:42:10-04:00
- performed the clone

The clone generated an error similar to:
```
TASK [satellite-clone : debug] *************************************************
Friday 07 April 2017  15:48:31 -0400 (0:00:00.044)       0:00:23.602 ********** 
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'root_free_space' is undefined\n\nThe error appears to have been in '/root/satellite-clone/roles/satellite-clone/tasks/pre_install_check.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug:\n  ^ here\n"}
```

**Comment by pgagne** [comment]
Can this be fixed by putting the path in quotes?

**Comment by johnpmitsch** [comment]
Note to John: Check that this is pulled into 6.2 https://bugzilla.redhat.com/show_bug.cgi?id=1436863

**Comment by johnpmitsch** [comment]
This still isn't in 6.2, I commented on the BZ to try and get this in 6.2.13

**Comment by johnpmitsch** [comment]
BZ is verified, closing
